### ISSUE TITLE
Use functions-differ from gitlab ci/cd

### ISSUE THREAD

**Issue by floriandu78** [haroldadmin/functions-differ#6]
Hi,

I've trying to make functions-differ works on my gitlab ci and it feels that it is not working. When i run functions-differ it seems that it is running forever. 

Here is the ci I implemented from .gitlab-ci.yml file.
```
test-differ:
  stage: test-differ
  image: node:12.20.1
  script:
    - npm install -g functions-differ --unsafe-perm=true
    - functions-differ
```

Has anyone experienced something similar in the past?

Kind regard,
Florian.
